# fly.toml app configuration file generated for visualized-elixir on 2026-10-06T09:31:50-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'visualized-elixir'
primary_region = 'ewr'
kill_signal = 'SIGTERM'

[build]
[env]
  PHX_HOST = 'visualized-elixir.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
